export const GET_CITY_DATA = "GET_CITY_DATA";
export const ADD_TO_FAVORITES = " ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = " REMOVE_FROM_FAVORITES";
export const GET_FIVE_DAYS_WEATHER = "GET_FIVE_DAYS_WEATHER";
